#!/usr/bin/env python3
"""One-command simulator verification. Logs are artifacts, stdout is a summary."""
import argparse
import fcntl
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import platform
import re
import signal
import shutil
import subprocess
import sys
import tempfile
import time

# Keep importability for contract tests that load this file by path.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import visual_regression
import process_cleanup

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / 'DerivedData/Build/Products/Debug-iphonesimulator/SwipeGo.app'
LOADED_IMPLEMENTATION = {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in (Path(__file__), Path(visual_regression.__file__), Path(process_cleanup.__file__))}
VERSION = 1
MAX_AGE = 24 * 60 * 60
UI = 'SwipeGoUITests/'
# Shared domain, design system, resources, scripts and unknown paths deliberately
# fall back to full. Keep this table alongside changes to navigation/case coverage.
PAGE_SUITES = {
    'SwipeGo/Features/Home/': ['HomeTests', 'HomeNavigationTests', 'HomeCoverStateTests', 'SettingsGlassTests', 'ReviewContinuityUITests'],
    'SwipeGo/Features/Permissions/': ['PermissionTests', 'WelcomeGlassTests', 'SettingsGlassTests', 'HomeTests'],
    'SwipeGo/Features/Comparison/': ['ComparisonUITests', 'DeletionReviewUITests'],
    'SwipeGo/Features/Reconciliation/': ['ReconciliationUITests', 'DeletionHistoryGlassTests'],
}


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def tree_digest(path):
    """Include names and executable bits; missing and empty artifacts are invalid."""
    path = Path(path)
    if not path.exists():
        raise ValueError(f'Missing artifact: {path}')
    if path.is_file():
        return digest(path)
    files = sorted(p for p in path.rglob('*') if p.is_file())
    if not files:
        raise ValueError(f'Empty artifact: {path}')
    items = [(str(p.relative_to(path)), p.stat().st_mode & 0o777, digest(p)) for p in files]
    return hashlib.sha256(json.dumps(items, sort_keys=True).encode()).hexdigest()


def tool_identities(search_path=None):
    # Compare executables used by this workflow, not unrelated provider aliases
    # prepended to PATH. A shadowing executable, symlink target or binary edit
    # changes the identity and invalidates reuse.
    names = ('bash', 'python3', 'git', 'xcodebuild', 'xcrun', 'xcodegen', 'swift', 'sips', 'ffmpeg', 'ffprobe', 'go')
    identities = {}
    for name in names:
        found = shutil.which(name, path=search_path)
        if found is None:
            identities[name] = None
        else:
            path = Path(found).resolve()
            identities[name] = {'path': str(path), 'sha256': digest(path)}
    return identities


def ignored_input(name):
    return (name.startswith(('docs/', '.agent-harness/runs/')) or
            name in {'.agent-harness/feature_list.json', '.agent-harness/progress.md', '.agent-harness/SPEC.md'})


def git_files(root=ROOT):
    raw = subprocess.check_output(['git', 'ls-files', '-z', '--cached', '--others', '--exclude-standard'], cwd=root)
    return sorted(set(os.fsdecode(p) for p in raw.split(b'\0') if p))


def source_hashes(root=ROOT):
    names = [n for n in git_files(root) if not ignored_input(n)]
    names += [str(p.relative_to(root)) for p in (root / 'Fixtures/generated').rglob('*') if p.is_file()]
    return {n: {'hash': digest(root / n), 'mode': (root / n).stat().st_mode & 0o777}
            for n in sorted(set(names)) if (root / n).is_file()}


def verify_preparation_inputs(before, after):
    # These two outputs are regenerated by explicit setup steps. All other
    # inputs must remain unchanged even during slow harness/toolchain checks.
    def stable(values):
        return {k: v for k, v in values.items() if not k.startswith(('Fixtures/generated/', 'SwipeGo.xcodeproj/'))}
    if stable(before) != stable(after):
        raise RuntimeError('Verification inputs changed during preparation; restart required')


def changed_files(base, root=ROOT):
    # No renames: both old and new paths must influence coverage.
    # Resolve an actual tree/ref first: a value such as --cached must not be
    # interpreted as a git-diff option that silently drops unstaged changes.
    tree = subprocess.check_output(['git', 'rev-parse', '--verify', '--end-of-options', base + '^{tree}'], cwd=root).decode().strip()
    raw = subprocess.check_output(['git', 'diff', '--no-renames', '--name-only', '-z', tree, '--'], cwd=root)
    raw += subprocess.check_output(['git', 'ls-files', '--others', '--exclude-standard', '-z'], cwd=root)
    return sorted(set(os.fsdecode(p) for p in raw.split(b'\0') if p))


def select_tests(paths, root=ROOT):
    suites = {UI + 'LaunchTests', 'SwipeGoTests'}
    for name in paths:
        if ignored_input(name):
            continue
        if name.startswith('SwipeGoTests/') and name.endswith('.swift'):
            continue  # Every unit test runs in changed mode.
        if name.startswith('SwipeGoUITests/') and name.endswith('.swift'):
            file = root / name
            # Deleted files and helpers may affect other classes: fail conservative.
            classes = re.findall(r'\bclass\s+(\w+)\s*:\s*XCTestCase', file.read_text()) if file.is_file() else []
            if not classes:
                return [], f'full: removed/shared UI test {name}'
            suites.update(UI + c for c in classes)
            continue
        matched = False
        for prefix, cases in PAGE_SUITES.items():
            if name.startswith(prefix):
                suites.update(UI + c for c in cases)
                matched = True
                break
        if not matched:
            return [], f'full: shared or unmapped path {name}'
    # Catch table drift before xcodebuild silently accepts nonexistent selectors.
    for suite in suites - {'SwipeGoTests'}:
        cls = suite.split('/')[1]
        if not any(re.search(r'\bclass\s+' + re.escape(cls) + r'\s*:\s*XCTestCase', p.read_text())
                   for p in (root / 'SwipeGoUITests').glob('*.swift')):
            return [], f'full: mapped suite no longer exists: {suite}'
    return sorted(suites), 'changed: related UI, launch smoke and all unit tests'


def parse_summary(data):
    keys = ('totalTestCount', 'passedTests', 'failedTests', 'skippedTests', 'expectedFailures')
    if not isinstance(data, dict) or any(type(data.get(k)) is not int or data[k] < 0 for k in keys):
        raise ValueError('Unknown xcresult summary count schema')
    if data.get('result') not in ('Passed', 'Failed', 'Skipped') or not isinstance(data.get('testFailures'), list):
        raise ValueError('Unknown xcresult summary result schema')
    if data['totalTestCount'] != sum(data[k] for k in keys[1:]):
        raise ValueError('Inconsistent xcresult counts')
    if data['totalTestCount'] == 0:
        raise ValueError('No tests executed')
    return {k: data[k] for k in (*keys, 'result', 'testFailures')}


def require_pass(data):
    result = parse_summary(data)
    if result['result'] != 'Passed' or any(result[k] for k in ('failedTests', 'skippedTests', 'expectedFailures')) or result['testFailures']:
        raise ValueError('Tests failed, were skipped or had expected failures; see xcresult')
    return result


def parse_tests(data):
    if not isinstance(data, dict) or not isinstance(data.get('testNodes'), list):
        raise ValueError('Unknown xcresult test tree schema')
    cases = []
    def walk(nodes):
        for node in nodes:
            if not isinstance(node, dict):
                raise ValueError('Malformed xcresult test node')
            if node.get('nodeType') == 'Test Case':
                url = node.get('nodeIdentifierURL', '')
                match = re.fullmatch(r'test://com\.apple\.xcode/SwipeGo/(SwipeGoTests|SwipeGoUITests)/([^/]+)/(.+)', url)
                if not match or not isinstance(node.get('result'), str):
                    raise ValueError('Unknown test identifier schema')
                cases.append({'id': '/'.join(match.groups()), 'result': node['result'],
                              'duration': node.get('durationInSeconds')})
            walk(node.get('children', []))
    walk(data['testNodes'])
    if not cases:
        raise ValueError('Empty xcresult test tree')
    return cases


def verify_coverage(cases, selectors):
    for selector in selectors or ['SwipeGoTests', 'SwipeGoUITests']:
        if not any(c['id'].startswith(selector.rstrip('/') + '/') and c['result'] == 'Passed' for c in cases):
            raise ValueError(f'Selected tests did not run: {selector}')


def attachments(manifest, directory):
    if not isinstance(manifest, list):
        raise ValueError('Unknown attachments manifest schema')
    result = []
    for case in manifest:
        if not isinstance(case.get('testIdentifier'), str) or not isinstance(case.get('attachments'), list):
            raise ValueError('Malformed attachment test entry')
        for item in case['attachments']:
            name = item.get('exportedFileName')
            if not isinstance(name, str) or Path(name).name != name or not (directory / name).is_file():
                raise ValueError('Missing or invalid exported attachment')
            result.append({'test': case['testIdentifier'], 'name': item.get('suggestedHumanReadableName', name),
                           'path': str(directory / name), 'failure': item.get('isAssociatedWithFailure', False)})
    return result


def reuse_allowed(args, environment):
    # Custom compiler/config overrides may include external files outside Git.
    # Their dependency graph is not proven, so they always require fresh tests.
    overrides = ('XCODE_XCCONFIG_FILE', 'SWIFT_EXEC', 'CC', 'CXX', 'SDKROOT', 'TOOLCHAINS')
    return (args.reuse and not args.fresh and environment.get('SWIPE_VERIFY_FRESH') != '1'
            and environment.get('SWIPE_VERIFICATION_MODE', 'simulator') == 'simulator'
            and not any(environment.get(key) for key in overrides))


def reusable(receipt, fingerprint, now=None):
    now = time.time() if now is None else now
    try:
        if (receipt['version'] != VERSION or receipt['status'] != 'passed' or receipt['mode'] != 'full' or
                receipt.get('reusedFrom') or receipt['fingerprint'] != fingerprint or
                not 0 <= now - receipt['finishedAt'] <= MAX_AGE):
            return False
        required = {'app', 'result', 'preflight', 'summary', 'tree', 'buildLog', 'testLog', 'permissionLog', 'attachments'}
        if set(receipt['artifacts']) != required:
            return False
        for artifact in receipt['artifacts'].values():
            if tree_digest(artifact['path']) != artifact['sha256']:
                return False
        if receipt['resultBundle'] != receipt['artifacts']['result']['path']:
            return False
        attachment_dir = Path(receipt['artifacts']['attachments']['path'])
        if receipt['attachments'] != attachments(json.loads((attachment_dir / 'manifest.json').read_text()), attachment_dir):
            return False
        raw = require_pass(json.loads(Path(receipt['artifacts']['summary']['path']).read_text()))
        if receipt['counts'] != raw:
            return False
        cases = parse_tests(json.loads(Path(receipt['artifacts']['tree']['path']).read_text()))
        verify_coverage(cases, [])
        if len(cases) != raw['totalTestCount'] or any(c['result'] != 'Passed' for c in cases):
            return False
        return True
    except (KeyError, TypeError, ValueError, OSError):
        return False


class Runner:
    def __init__(self, directory, report):
        self.directory, self.report = directory, report

    def run(self, phase, argv, *, check=True, timeout=1800):
        log = self.directory / f'{len(self.report["steps"]):02d}-{phase}.log'
        step = {'phase': phase, 'argv': [str(x) for x in argv], 'log': str(log)}
        self.report['steps'].append(step)
        start = time.monotonic()
        with log.open('w') as stream:
            proc = subprocess.Popen(step['argv'], cwd=ROOT, stdout=stream, stderr=subprocess.STDOUT, start_new_session=True)
            try:
                step['exitCode'] = proc.wait(timeout=timeout)
            except BaseException:
                process_cleanup.stop_process_group(proc)
                step['exitCode'] = proc.returncode
                raise
            finally:
                step['seconds'] = round(time.monotonic() - start, 2)
        if check and step['exitCode']:
            raise RuntimeError(f'{phase} failed ({step["exitCode"]}); {log}')
        return log

    def capture(self, phase, argv):
        return self.run(phase, argv, timeout=120).read_text().strip()


def write_report(directory, report):
    (directory / 'receipt.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
    lines = [f'# Verification: {report["status"]}', '',
             f'- Mode: {report.get("mode", "unknown")} ({report.get("selectionReason", "")})',
             f'- Wall time: {report["seconds"]:.1f}s',
             f'- Commit: {report.get("head", "unknown")}',
             f'- Tests: {json.dumps(report.get("counts", {}), ensure_ascii=False)}',
             f'- Environment: {json.dumps(report.get("environment", {}), ensure_ascii=False)}']
    if report.get('reusedFrom'):
        lines += [f'- Reused original report: {report["reusedFrom"]}', f'- Original finish time (Unix): {report["originalFinishedAt"]}']
    if report.get('error'):
        lines += ['', '## Failure', '', report['error']]
    for failure in report.get('counts', report.get('preflightCounts', {})).get('testFailures', []):
        lines += [f'- {failure.get("testIdentifierString", "unknown")}: {failure.get("failureText", "")}']
    lines += ['', '## Logs and results', '']
    for step in report['steps']:
        lines += [f'- [{step["phase"]}]({step["log"]}): exit {step.get("exitCode", "not started")}']
    if report.get('resultBundle'):
        lines += [f'- xcresult: {report["resultBundle"]}']
    lines += ['', '## Visual comparison', '', json.dumps(report.get('visual', {}).get('status', 'not_run'))]
    for item in report.get('visual', {}).get('items', []):
        if item['status'] != 'unchanged':
            lines += [f'- {item["status"]}: {item["key"]}; changed fraction: {item.get("changedFraction", "n/a")}']
            for label in ('baseline', 'actual'):
                if item.get(label):
                    lines += [f'  [{label}]({item[label]})']
    lines += ['', '## Visual review evidence', '', 'Pixel differences flag review; passing tests do not prove aesthetic quality.']
    for item in report.get('attachments', []):
        lines += [f'- {item["test"]}: [{item["name"]}]({item["path"]})']
    (directory / 'evidence.md').write_text('\n'.join(lines) + '\n')
    compact_keys = ('version', 'status', 'mode', 'selectionReason', 'head', 'startedAt', 'finishedAt', 'seconds',
                    'counts', 'preflightCounts', 'countsByTarget', 'error', 'reusedFrom', 'originalFinishedAt', 'resultBundle', 'deviceVerification')
    compact = {key: report[key] for key in compact_keys if key in report}
    compact['environment'] = {k: report.get('environment', {}).get(k) for k in ('xcode', 'simulator')}
    compact['details'] = str(directory / 'receipt.json')
    compact['evidence'] = str(directory / 'evidence.md')
    compact['fingerprintHash'] = hashlib.sha256(json.dumps(report.get('fingerprint', {}), sort_keys=True).encode()).hexdigest()
    compact['failedSteps'] = [{k: step.get(k) for k in ('phase', 'exitCode', 'log')} for step in report['steps'] if step.get('exitCode') != 0]
    visual = report.get('visual', {})
    compact['visual'] = {'status': visual.get('status', 'not_run'),
                         'changed': [item for item in visual.get('items', []) if item['status'] != 'unchanged']}
    (directory / 'summary.json').write_text(json.dumps(compact, ensure_ascii=False, indent=2) + '\n')
    brief = [f'# Verification: {report["status"]}', '',
             f'- Mode: {report.get("mode", "unknown")} — {report.get("selectionReason", "")}',
             f'- Time: {report["seconds"]:.1f}s; commit: {report.get("head", "unknown")}',
             f'- Tests: {report.get("counts", {}).get("passedTests", 0)} passed / {report.get("counts", {}).get("failedTests", 0)} failed',
             f'- Targets: {json.dumps(report.get("countsByTarget", {}))}',
             f'- Visual: {compact["visual"]["status"]}']
    if 'preflightCounts' in report:
        pre = report['preflightCounts']
        brief += [f'- Permission preflight: {pre["passedTests"]} passed / {pre["failedTests"]} failed']
    if 'counts' not in report:
        brief += ['- Main suite: not executed or no valid result']
    if report.get('reusedFrom'):
        brief += [f'- Reused: {report["reusedFrom"]}; original finishedAt: {report["originalFinishedAt"]}']
    if report.get('error'):
        brief += ['', report['error']]
    for step in compact['failedSteps']:
        brief += [f'- [{step["phase"]}]({step["log"]}): exit {step["exitCode"]}']
    for failure in report.get('counts', report.get('preflightCounts', {})).get('testFailures', []):
        brief += [f'- {failure.get("testIdentifierString", "unknown")}: {failure.get("failureText", "")}']
    for item in compact['visual']['changed']:
        brief += [f'- {item["status"]}: {item["key"]}']
        for label in ('baseline', 'actual'):
            if item.get(label): brief += [f'  [{label}]({item[label]})']
    brief += ['', f'[All screenshots and logs]({directory / "evidence.md"}) · [Detailed receipt]({directory / "receipt.json"})']
    (directory / 'report.md').write_text('\n'.join(brief) + '\n')



def collect_result(runner, name, bundle, directory, report):
    # Export before summary parsing/assertions, including all-failed or
    # unknown summary schemas, so diagnostics cannot be lost.
    output = directory / (name + '-attachments')
    runner.run(name + '-attachments', ['xcrun', 'xcresulttool', 'export', 'attachments', '--path', str(bundle), '--output-path', str(output)])
    report['attachments'] = attachments(json.loads((output / 'manifest.json').read_text()), output)
    raw = json.loads(runner.capture(name + '-summary', ['xcrun', 'xcresulttool', 'get', 'test-results', 'summary', '--path', str(bundle)]))
    summary_path = directory / (name + '-summary.json')
    summary_path.write_text(json.dumps(raw, indent=2) + '\n')
    report['counts' if name == 'tests' else 'preflightCounts'] = parse_summary(raw)
    return raw, summary_path


def execute(args, directory, report, runner):
    if any(digest(path) != sha for path, sha in LOADED_IMPLEMENTATION.items()):
        raise RuntimeError('Loaded verification implementation changed; restart required')
    initial_sources = source_hashes()
    os.environ['HARNESS_EVALUATOR_EVIDENCE_BASELINE'] = 'F001'
    # A caller cannot silently weaken the aggregate pass contract.
    os.environ.pop('HARNESS_SKIP_TEST_LAYERS', None)
    developer = os.environ.get('DEVELOPER_DIR')
    if developer is None:
        developer = subprocess.check_output(['xcode-select', '-p'], text=True).strip()
        if not (Path(developer) / 'Platforms/iPhoneOS.platform').is_dir():
            developer = '/Applications/Xcode.app/Contents/Developer'
    if developer.endswith('.app'):
        developer += '/Contents/Developer'
    os.environ['DEVELOPER_DIR'] = developer
    print('VERIFY: prerequisites and Python/harness checks (logs saved)', flush=True)
    runner.run('harness', ['.agent-harness/scripts/init.sh'])
    runner.run('doctor', ['scripts/doctor.sh'])
    runner.run('fixtures', ['python3', 'scripts/seed-fixtures.py', '--seed', '27'])
    runner.run('python-tests', ['python3', '-m', 'unittest', 'discover', '-s', 'tests', '-v'])
    runner.run('project', ['xcodegen', 'generate', '--spec', 'project.yml'])
    spec = importlib.util.spec_from_file_location('simulator_selector', ROOT / 'scripts/select-simulator.py')
    selector = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(selector)
    selected = selector.select_device(json.loads(runner.capture('inventory', ['xcrun', 'simctl', 'list', '-j'])), os.environ.get('SWIPE_SIMULATOR_UDID'))
    env_keys = ('DEVELOPER_DIR', 'LANG', 'LC_ALL', 'LC_CTYPE', 'TZ', 'SDKROOT', 'TOOLCHAINS', 'SWIFT_EXEC', 'CC', 'CXX', 'XCODE_XCCONFIG_FILE')
    environment = {'xcode': runner.capture('xcode', ['xcodebuild', '-version']),
                   'xcodegen': runner.capture('xcodegen', ['xcodegen', '--version']),
                   'python': sys.version, 'macOS': platform.platform(), 'tools': tool_identities(),
                   'simulator': {k: v for k, v in selected.items() if k != 'state'},
                   'variables': {k: os.environ.get(k) for k in env_keys}, 'seed': 27, 'visualBaseline': str(args.baseline.resolve()),
                   'visualBaselineHash': tree_digest(args.baseline) if args.baseline.exists() else None}
    config = os.environ.get('XCODE_XCCONFIG_FILE')
    if config:
        environment['xcconfigHash'] = digest(config)
    report['environment'] = environment
    report['head'] = subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True).strip()
    report['changedPaths'] = changed_files(args.base)
    selectors, reason = select_tests(report['changedPaths']) if args.changed else ([], 'explicit full verification')
    report.update(mode='changed' if selectors else 'full', selectors=selectors, selectionReason=reason)
    sources = source_hashes()
    verify_preparation_inputs(initial_sources, sources)
    fingerprint = {'sources': sources, 'environment': environment, 'version': VERSION}
    report['fingerprint'] = fingerprint
    pointer = ROOT / '.build/verification/latest-full.json'
    previous = None
    if reuse_allowed(args, os.environ):
        try:
            candidate = Path(json.loads(pointer.read_text())['report'])
            receipt = json.loads(candidate.read_text())
            if reusable(receipt, fingerprint):
                previous = (candidate, receipt)
        except (ValueError, KeyError, TypeError, OSError):
            pass
    sid = selected['udid']
    if selected['state'] == 'Booted':
        runner.run('shutdown', ['xcrun', 'simctl', 'shutdown', sid])
    runner.run('boot', ['xcrun', 'simctl', 'bootstatus', sid, '-b'])
    if previous:
        path, receipt = previous
        report.update(reusedFrom=str(path), originalFinishedAt=receipt['finishedAt'], counts=receipt['counts'],
                      attachments=receipt['attachments'], resultBundle=receipt['resultBundle'], countsByTarget=receipt.get('countsByTarget', {}))
        print(f'VERIFY: reuse full test evidence from {path.parent.name}; live install/launch next', flush=True)
    else:
        # A fresh attempt invalidates old evidence, including when it fails.
        pointer.unlink(missing_ok=True)
        print(f'VERIFY: {report["mode"]}; {reason}; build once, run serial tests', flush=True)
        runner.run('remove-runner', ['xcrun', 'simctl', 'uninstall', sid, 'dev.armstrong.swipego.uitests.xctrunner'])
        options = ['-project', 'SwipeGo.xcodeproj', '-scheme', 'SwipeGo', '-configuration', 'Debug',
                   '-destination', f'platform=iOS Simulator,id={sid}', '-derivedDataPath', str(ROOT / 'DerivedData'),
                   '-parallel-testing-enabled', 'NO', 'CODE_SIGNING_ALLOWED=YES', 'CODE_SIGN_IDENTITY=-']
        build_log = runner.run('build', ['xcodebuild', *options, 'build-for-testing'])
        bundles = [('permission', directory / 'PermissionSetup.xcresult', [UI + 'PermissionTests/testFullAccessQueriesRealLibrary']),
                   ('tests', directory / 'Tests.xcresult', selectors)]
        logs = {}
        for name, bundle, tests in bundles:
            report['resultBundle'] = str(bundle)
            log = runner.run(name, ['xcodebuild', *options, '-resultBundlePath', str(bundle),
                                   *['-only-testing:' + test for test in tests], 'test-without-building'], check=False)
            logs[name] = log
            command_ok = report['steps'][-1]['exitCode'] == 0
            raw, summary_path = collect_result(runner, name, bundle, directory, report)
            require_pass(raw)
            if not command_ok:
                raise RuntimeError(f'{name}: xcodebuild failed despite summary; {log}')
            if 'SwiftData.ModelContext: Unbinding' in log.read_text():
                raise RuntimeError(f'{name}: SwiftData ModelContext crossed its creation queue; {log}')
            if name == 'tests':
                tree = json.loads(runner.capture('test-tree', ['xcrun', 'xcresulttool', 'get', 'test-results', 'tests', '--path', str(bundle)]))
                tree_path = directory / 'tests-tree.json'
                tree_path.write_text(json.dumps(tree, indent=2) + '\n')
                cases = parse_tests(tree)
                verify_coverage(cases, selectors)
                if len(cases) != raw['totalTestCount']:
                    raise ValueError('Test tree/count mismatch')
                report['cases'] = cases
                report['countsByTarget'] = {target: sum(c['id'].startswith(target + '/') for c in cases) for target in ('SwipeGoTests', 'SwipeGoUITests')}
        artifacts = {'app': APP, 'result': bundles[1][1], 'preflight': bundles[0][1],
                     'summary': summary_path, 'tree': tree_path, 'buildLog': build_log,
                     'testLog': logs['tests'], 'permissionLog': logs['permission'], 'attachments': directory / 'tests-attachments'}
        report['artifacts'] = {k: {'path': str(v), 'sha256': tree_digest(v)} for k, v in artifacts.items()}
    runner.run('install', ['xcrun', 'simctl', 'install', sid, str(APP)])
    runner.run('launch', ['xcrun', 'simctl', 'launch', '--terminate-running-process', sid, 'dev.armstrong.swipego'])
    if os.environ.get('SWIPE_VERIFICATION_MODE', 'simulator') == 'device':
        runner.run('device-vision', ['scripts/verify-device-vision.sh'])
    expected_app_hash = previous[1]['artifacts']['app']['sha256'] if previous else report['artifacts']['app']['sha256']
    if tree_digest(APP) != expected_app_hash:
        raise RuntimeError('Built app changed during execution')
    if source_hashes() != sources:
        raise RuntimeError('Verification inputs changed during execution; rerun required')
    report['visual'] = visual_regression.compare(report.get('attachments', []), args.baseline, directory / 'visual-baselines', complete=report['mode'] == 'full' or bool(previous), exercised=[c['id'].split('/', 1)[1] + '()' for c in report.get('cases', [])])
    if (tree_digest(args.baseline) if args.baseline.exists() else None) != environment['visualBaselineHash'] or source_hashes() != sources:
        raise RuntimeError('Verification inputs or visual baseline changed during execution')
    if report['visual']['status'] == 'needs_review':
        raise RuntimeError('Visual baseline needs review')
    report['deviceVerification'] = 'passed bundled Vision gate' if os.environ.get('SWIPE_VERIFICATION_MODE') == 'device' else 'deferred: F018'
    report['status'] = 'passed'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--changed', action='store_true', help='Select related tests from diff + untracked files')
    modes.add_argument('--full', action='store_true', help='Run all tests (default)')
    parser.add_argument('--base', default='HEAD', help='Git ref for changed scope, default HEAD')
    parser.add_argument('--reuse', action='store_true', help='Allow intact matching full evidence less than 24h old')
    parser.add_argument('--fresh', action='store_true', help='Force execution even if reuse was requested')
    parser.add_argument('--baseline', type=Path, default=ROOT / 'tests/visual-baselines', help='Reviewed visual baseline directory (optional until first approval)')
    parser.add_argument('--accept-visual-baseline', type=Path, metavar='SUMMARY_JSON', help='Explicitly approve screenshots from a reviewed report; does not run tests')
    args = parser.parse_args(argv)
    if args.accept_visual_baseline:
        approval_lock_path = ROOT / '.build/verification/run.lock'
        approval_lock_path.parent.mkdir(parents=True, exist_ok=True)
        approval_lock = approval_lock_path.open('a')
        try:
            fcntl.flock(approval_lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            count = visual_regression.accept_baseline(args.accept_visual_baseline, args.baseline)
            print(f'VISUAL_BASELINE_APPROVED: {count} images in {args.baseline}')
            return 0
        except (ValueError, OSError, KeyError, TypeError) as error:
            print(f'VISUAL_BASELINE_FAILED: {error}', file=sys.stderr)
            return 1
        finally:
            approval_lock.close()
    build = ROOT / '.build/verification'
    build.mkdir(parents=True, exist_ok=True)
    directory = Path(tempfile.mkdtemp(prefix=time.strftime('%Y%m%dT%H%M%S-'), dir=build))
    report = {'version': VERSION, 'status': 'failed', 'startedAt': time.time(), 'steps': []}
    runner = Runner(directory, report)
    lock = (build / 'run.lock').open('a')
    acquired = False
    signal.signal(signal.SIGTERM, lambda *_: (_ for _ in ()).throw(KeyboardInterrupt()))
    try:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            acquired = True
        except BlockingIOError:
            raise RuntimeError('Another verification owns the simulator/build lock; wait for its report')
        if os.environ.get('SWIPE_VERIFICATION_MODE', 'simulator') not in ('simulator', 'device'):
            raise ValueError('SWIPE_VERIFICATION_MODE must be simulator or device')
        execute(args, directory, report, runner)
    except (Exception, KeyboardInterrupt) as error:
        report['error'] = str(error) or 'Interrupted'
        if acquired:
            (build / 'latest-full.json').unlink(missing_ok=True)
    finally:
        report['finishedAt'] = time.time()
        report['seconds'] = report['finishedAt'] - report['startedAt']
        write_report(directory, report)
        if acquired:
            (build / 'latest.json').write_text(json.dumps({'report': str(directory / 'summary.json')}) + '\n')
            if report['status'] == 'passed' and report['mode'] == 'full' and not report.get('reusedFrom') and os.environ.get('SWIPE_VERIFICATION_MODE', 'simulator') == 'simulator':
                (build / 'latest-full.json').write_text(json.dumps({'report': str(directory / 'receipt.json')}) + '\n')
        lock.close()
    counts = report.get('counts', report.get('preflightCounts', {}))
    print(f'VERIFY_{report["status"].upper()}: {"main" if "counts" in report else "preflight/setup"} {counts.get("passedTests", 0)} passed, {counts.get("failedTests", 0)} failed; {report["seconds"]:.1f}s')
    if report.get('error'):
        print(report['error'])
    print(f'REPORT: {directory / "report.md"}\nJSON: {directory / "summary.json"}')
    return 0 if report['status'] == 'passed' else 1


if __name__ == '__main__':
    sys.exit(main())
